name: android merge request

on:
  workflow_call:
    inputs:
      java_version:
        default: '11'
        required: false
        type: string

jobs:
  cheks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: detekt lint tests
      run: ./gradlew check --no-daemon
      
