name: ios merge request

on:
  workflow_call:
    inputs:
      xcodeproj_path:
        required: false
        type: string
      scheme_name:
        required: false
        type: string

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Bundle install
        run: bundle install

      - name: tests lint
        env:
          XCODEPROJ_PATH: ${{ inputs.xcodeproj_path }}
          SCHEME_NAME: ${{ inputs.scheme_name }}
        run: bundle exec fastlane check

  swiftlint:
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:0.47.0
    steps:
      - uses: actions/checkout@v3
      - run: swiftlint --quiet


