name: publish android aar

on:
  workflow_call:
    secrets:
      gpg_key:
        required: true
      sign_ossrh_gradle_properties:
        required: true
    inputs:
      java_version:
        default: '11'
        required: false
        type: string
      file_with_version_name:
        default: 'gradle.properties'
        required: false
        type: string

jobs:
  publish:
    name: Release AAR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: gradle

      - name: Retrieve the secret and decode it to a file
        env:
          GPG_KEY: ${{ secrets.gpg_key }}
        run: echo "$GPG_KEY" | base64 --decode > $HOME/secring.gpg

      - name: Retrieve the gradle.properties
        env:
            SIGN_OSSRH_GRADLE_PROPERTIES: ${{ secrets.sign_ossrh_gradle_properties }}
        run: |
          mkdir -p ~/.gradle
          echo -en "$SIGN_OSSRH_GRADLE_PROPERTIES" > ~/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check version (fail if version tag is exists)
        id: version
        env:
          FILE_WITH_VERISON_NAME: ${{ inputs.file_with_version_name }}
        run: |
          TAG_NAME=$(grep -oP "^VERSION_NAME=\K([\d.]+)" ${FILE_WITH_VERISON_NAME})
          (! git ls-remote --tags | grep refs/tags/${TAG_NAME})
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: upload artifacts
        id: artifacts
        run: |
          ./gradlew uploadArchives -Psigning.secretKeyRingFile=$HOME/secring.gpg -Prelease
          AAR_PATH=$(find . -name *.aar | tail -n 1)
          FILE_NAME=${AAR_PATH##*/}
          echo "::set-output name=aar_path::$AAR_PATH"
          echo "::set-output name=file_name::$FILE_NAME"

      - name: push tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.version.outputs.tag_name }}

      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          release_name: ${{ steps.version.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload AAR 🗳
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifacts.outputs.aar_path }}
          asset_name: ${{ steps.artifacts.outputs.file_name }}
          asset_content_type: application/aar
